Multi source listeners
chark/scriptable-events pull request #23
Opened 2022-08-03 13:25 UTC by ChaosCrafter

This changes listeners to accept multiple events (of a compatible type)
It replaces the existing listener/event mapping with a listener/List<event> mapping. 
The old event property is retained but concealed - I suggest it should be removed fully when the project next rolls major version (i.e. when a breaking change is reasonable to add)
A test has been added to make sure multi-event listening works for each event type.
The only shortfall I am aware of is that it does not check if you are in Editor mode (the detection of editor mode is not available during serialisation.)

I should note I have not tested this in an Odin-compatible environment.

I hope you find this useful.

2022-08-03 17:20 UTC, Edvinas01 requested changes
...ignore the failing tests, it seems that GitHub actions doesn't pass secrets to fork PRs, which prevents the tests from running on the action due to needing access to the Unity license file (which is a secret).

2022-08-03 17:20 UTC, Edvinas01 commented on Packages/com.chark.scriptable-events/Runtime/BaseScriptableEventListener.cs
> +            scriptableEvents?.ForEach(scriptableEvent => scriptableEvent.AddListener(this));
I'm not sure if `?` is needed, as the `scriptableEvents` list is always initialized in and will never be `null`. Other thank that, looks good 👍

2022-08-03 17:20 UTC, Edvinas01 commented on Packages/com.chark.scriptable-events/Runtime/BaseScriptableEventListener.cs
> +            if (scriptableEvent != null)
I'd recommend to test against `false` instead of `null` as `scriptableEvent` is an `Object` and it might not be `null` (even if the event is destroyed).

2022-08-03 17:20 UTC, Edvinas01 commented on Packages/com.chark.scriptable-events/Runtime/BaseScriptableEventListener.cs
> +            // Ideally we should only do this in Editor mode but Application.isPlaying will not work during serialisation
I'd recommend to add a an `if` to check if the app is running. If it is, then it would skip the logic below:
```cs
if (Application.isPlaying)
{
    return;
}
```

2022-08-03 17:20 UTC, Edvinas01 commented on Packages/com.chark.scriptable-events/Tests/Editor/ScriptBuilderTest.cs
> +        public string NormaliseCRs(string source)
Nice, I haven't thought about this, thank you for adding it ❤️ 

The only thing I'd recommend to change here is the `public` modifier to `private` and move this method to the bottom of this class (I try to keep `public` methods at the top [below Unity Lifecycle methods] and `private` methods at the bottom of classes).

I guess this method could also be made `static` for completeness...

2022-08-03 22:21 UTC, ChaosCrafter commented on Packages/com.chark.scriptable-events/Runtime/BaseScriptableEventListener.cs
> +            // Ideally we should only do this in Editor mode but Application.isPlaying will not work during serialisation
I've now added that.  Strangely when I initially had it, it was throwing an exception when it got to that point.

2022-08-04 05:51 UTC, Edvinas01 approved these changes
Good work! Thank you for the PR ❤️

2022-08-04 05:51 UTC, merged